// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhonncmgmcpkkfekeksi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJob25uY21nbWNwa2tmZWtla3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTg2MTksImV4cCI6MjA3MjQ3NDYxOX0.Zpt4Lp_ZBczbX8yLfqWuAeqISwuSY2rPKLsZmNqUOHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});